# Generated by Django 4.0.2 on 2022-08-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UltimateCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=13)),
                ('promo_applied', models.BooleanField(default=False)),
                ('promo', models.CharField(default='', max_length=12)),
                ('promo_attempts', models.IntegerField(default=0)),
                ('applied_on', models.DateTimeField(default=None, null=True)),
                ('purchased', models.BooleanField(default=False)),
                ('purchased_on', models.DateTimeField(default=None, null=True)),
                ('price_paid', models.IntegerField(default=-1)),
            ],
        ),
    ]
