# Generated by Django 4.0.2 on 2022-08-28 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UltimateCourse',
            new_name='UltimateCourseCustomer',
        ),
    ]
